stages:
  - build
  - deploy

build-docker:
  image: docker:latest  
  stage: build  
  services:
    - docker:dind
  variables:
    CONTAINER_IMAGE: ${DOCKER_REGISTRY_USER}/my-test:${CI_COMMIT_SHORT_SHA}
  before_script:
    - docker login -u "${DOCKER_REGISTRY_USER}" -p "${DOCKER_REGISTRY_PASSWORD}"
  script: 
    - docker build -t ${CONTAINER_IMAGE} .
    - docker push "${CONTAINER_IMAGE}"

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
    - kubectl apply -f deployment.yaml
    - kubectl expose deployment gitlab-test --port=5000 --target-port=5000 --type='LoadBalancer' --name='my-lbs' 
